# Generated by Django 4.2.11 on 2024-04-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adltest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campo1', models.CharField(max_length=100)),
                ('valor1', models.IntegerField(default=0)),
            ],
        ),
    ]
